[package]
name = "terminus"
version = "2.3.0"
edition = "2021"
description = "CLI tool to check URL accessibility using various HTTP methods with proxy, headers, cookies, and HTTP/1-2 support."
license = "GPL-3.0"
authors = ["Gilles Biagomba<gilles.infosec@gmail.com>"]
repository = "https://github.com/your_github/terminus"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.12.23", features = ["blocking", "cookies", "http2"] }
rayon = "1.5.1"
anyhow = "1.0"
log = "0.4"        # Add logging dependency
env_logger = "0.11.8"

[build-dependencies]